Dropped unnecessary xODR reference that was causing compilation errors.
git-svn-id: https://opendentalsoft.com:23793/svn/opendental/head@13869 098d0599-7f2b-0410-95a5-ad30ac85393a